// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zekigsebsmsukrummrzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpla2lnc2Vic21zdWtydW1tcnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDY0OTAsImV4cCI6MjA1ODQyMjQ5MH0.SBqpiV6cDX_clnEidEZfFipjhGVnSu0hwLrW9tf4myQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Regular client for normal operations
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);